// Generates the SDK's two tables from the Flutter SDK itself:
//
//   dart run tool/generate_tables.dart [<flutter root>]
//
// lib/src/icon_names.g.dart — icon names by code point (below).
// lib/src/framework_painters.g.dart — the names of the framework's own
// `CustomPainter`s (input borders, scrollbars, switches, spinners…), so the
// capture can tell them from an app's own drawing, which it records as an
// opaque `Canvas`.
//
// The recording names an icon (MOBILE-REPLAY-FORMAT §10): `iconSet` plus the
// icon's name, because Flutter's Material font numbers its glyphs differently
// from the Material Icons font the dashboard draws with. A running app only
// has `IconData.codePoint`, so the SDK carries a code point → name table,
// read here out of `material/icons.dart` (the name is in each constant's doc
// comment: `<i class="material-icons md-36">10k</i>`) and `cupertino/icons.dart`.
//
// Both files are part of the Flutter SDK, BSD-3-Clause (Copyright 2014 The
// Flutter Authors); only the names and code points are copied. The table is
// packed into two strings, `name:cp,cp;…`, and parsed on first use, so it
// costs a few tens of kilobytes in the app rather than a map literal's
// hundreds.
import 'dart:io';

void main(List<String> args) {
  final root = args.isNotEmpty ? args.first : _flutterRoot();
  final material = File('$root/packages/flutter/lib/src/material/icons.dart').readAsStringSync();
  final cupertino = File('$root/packages/flutter/lib/src/cupertino/icons.dart').readAsStringSync();
  final version = _flutterVersion(root);

  final materialNames = _parse(material, RegExp(r'<i class="material-icons[^"]*">([^<]+)</i>'));
  // CupertinoIcons lists its pre-1.0 names first and the 1.0 names (the SF
  // Symbol-like ones: `heart_fill`, not `heart_solid`) after them, so the
  // last constant for a code point wins there.
  final cupertinoNames = _parse(cupertino, null, lastWins: true);

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_icon_names.dart from Flutter $version. Do not edit.')
    ..writeln('//')
    ..writeln('// Icon names and code points from the Flutter SDK (BSD-3-Clause,')
    ..writeln('// Copyright 2014 The Flutter Authors): packages/flutter/lib/src/material/icons.dart')
    ..writeln('// and packages/flutter/lib/src/cupertino/icons.dart.')
    ..writeln()
    ..writeln('/// Flutter version the table was read from.')
    ..writeln("const String iconTableFlutterVersion = '$version';")
    ..writeln()
    ..writeln('/// Material Icons: `name:codepoint,codepoint;…`, code points in hex.')
    ..writeln("const String packedMaterialIcons = '${_pack(materialNames)}';")
    ..writeln()
    ..writeln('/// CupertinoIcons: the same, with the icon names CupertinoIcons uses.')
    ..writeln("const String packedCupertinoIcons = '${_pack(cupertinoNames)}';");
  File('lib/src/icon_names.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('material: ${materialNames.length} code points, cupertino: ${cupertinoNames.length}');

  final painters = _frameworkPainters('$root/packages/flutter/lib/src');
  final list = StringBuffer()
    ..writeln('// GENERATED by tool/generate_tables.dart from Flutter $version. Do not edit.')
    ..writeln()
    ..writeln("/// Every `CustomPainter` class in the Flutter framework (packages/flutter/lib/src),")
    ..writeln('/// by name: chrome the framework draws, never an app\'s own drawing.')
    ..writeln('const Set<String> frameworkPainters = {')
    ..writeAll(painters.map((name) => "  '$name',\n"))
    ..writeln('};');
  File('lib/src/framework_painters.g.dart').writeAsStringSync(list.toString());
  stdout.writeln('framework painters: ${painters.length}');
}

/// Classes that are a `CustomPainter`, directly or through another one.
List<String> _frameworkPainters(String sourceRoot) {
  final supertypes = <String, String>{};
  final declaration = RegExp(r'class\s+(\w+)(?:<[^{]*?>)?\s+((?:extends|implements|with)[^{]*)\{');
  for (final entity in Directory(sourceRoot).listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    for (final match in declaration.allMatches(entity.readAsStringSync())) {
      supertypes[match.group(1)!] = match.group(2)!;
    }
  }
  final painters = <String>{'CustomPainter'};
  var grew = true;
  while (grew) {
    grew = false;
    supertypes.forEach((name, parents) {
      if (painters.contains(name)) return;
      final words = RegExp(r'\w+').allMatches(parents).map((m) => m.group(0)!);
      if (words.any(painters.contains)) {
        painters.add(name);
        grew = true;
      }
    });
  }
  return (painters..remove('CustomPainter')).toList()..sort();
}

/// Code point → name, the first constant for a code point winning.
Map<int, String> _parse(String source, RegExp? namePattern, {bool lastWins = false}) {
  final result = <int, String>{};
  final constant = RegExp(r'static const IconData (\w+) = IconData\(\s*(0x[0-9a-fA-F]+)');
  var lastEnd = 0;
  for (final match in constant.allMatches(source)) {
    // The doc comment between the previous constant and this one.
    final comment = source.substring(lastEnd, match.start);
    lastEnd = match.end;
    final named = namePattern?.allMatches(comment).toList() ?? const [];
    final name = named.isNotEmpty ? named.last.group(1)! : match.group(1)!;
    final codePoint = int.parse(match.group(2)!.substring(2), radix: 16);
    if (!RegExp(r'^[A-Za-z0-9._-]{1,64}$').hasMatch(name)) continue;
    if (lastWins) {
      result[codePoint] = name;
    } else {
      result.putIfAbsent(codePoint, () => name);
    }
  }
  return result;
}

String _pack(Map<int, String> names) {
  final byName = <String, List<int>>{};
  for (final entry in names.entries) {
    byName.putIfAbsent(entry.value, () => <int>[]).add(entry.key);
  }
  final keys = byName.keys.toList()..sort();
  return keys.map((name) {
    final points = byName[name]!..sort();
    return '$name:${points.map((p) => p.toRadixString(16)).join(',')}';
  }).join(';');
}

String _flutterRoot() {
  final which = Process.runSync('which', ['flutter']).stdout.toString().trim();
  final resolved = File(which).resolveSymbolicLinksSync();
  return File(resolved).parent.parent.path;
}

String _flutterVersion(String root) {
  final file = File('$root/bin/cache/flutter.version.json');
  if (file.existsSync()) {
    final match = RegExp(r'"frameworkVersion"\s*:\s*"([^"]+)"').firstMatch(file.readAsStringSync());
    if (match != null) return match.group(1)!;
  }
  final version = File('$root/version');
  return version.existsSync() ? version.readAsStringSync().trim() : 'unknown';
}
